#!/usr/bin/env python3
"""Download and build an isolated TRSM runtime from pinned upstream sources.

Run with Python 3.13. A fresh prefix is required on the first invocation;
--resume reuses verified completed steps belonging to this installer.
"""

import argparse
from contextlib import contextmanager
from datetime import datetime, timezone
import fcntl
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
COMPONENTS = ("python", "datasets", "higgstools", "micromegas", "bsmpt", "mg5")
PROCESSES = ("hh", "hhh", "gg_heta0", "pp_eta0Z")
STATE_NAME = "bootstrap-state.json"


class SetupError(RuntimeError):
    pass


def sha256(path):
    with Path(path).open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def write_json(path, value):
    path = Path(path)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w") as stream:
        json.dump(value, stream, indent=2, sort_keys=True, allow_nan=False)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    temporary.replace(path)


def source_fingerprint():
    files = [Path(__file__), ROOT / "tools/stage_bsmpt_v2.py",
             ROOT / "tools/runtime_manifest.py", ROOT / "DM/setup_micromegas.sh",
             ROOT / "DM/main.c", ROOT / "DM/trsm_loop.c", ROOT / "DM/data.par",
             ROOT / "MG5stuff/loop_sm_twoscalar_generic.tar.gz"]
    for directory in ("config", "DM/patches", "DM/models/h4GOn", "BSMPT"):
        files.extend(p for p in (ROOT / directory).rglob("*")
                     if p.is_file() and not p.name.startswith(".")
                     and "__pycache__" not in p.parts)
    return {str(p.relative_to(ROOT)): sha256(p) for p in sorted(set(files))}


def extract_source(archive, destination, top_directory, *, ufo=False):
    """Extract one source tree, rejecting traversal and out-of-tree links."""
    destination = Path(destination)
    if destination.exists():
        raise SetupError(f"Refusing to extract over {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".extract-", dir=destination.parent) as tmp:
        def source_filter(member, path):
            parts = Path(member.name).parts
            if any(p.startswith("._") or p == ".DS_Store" for p in parts):
                return None
            if ufo and ("__pycache__" in parts or member.name.endswith((".pkl", ".pyc", ".pyo", "~"))):
                return None
            return tarfile.data_filter(member, path)
        with tarfile.open(archive) as source:
            source.extractall(tmp, filter=source_filter)
        tree = Path(tmp) / top_directory
        if not tree.is_dir() or tree.is_symlink():
            raise SetupError(f"Archive has no source directory {top_directory!r}: {archive}")
        tree.rename(destination)


def download_archive(spec, cache):
    cache = Path(cache)
    cache.mkdir(parents=True, exist_ok=True)
    target = cache / spec["filename"]
    if not target.exists():
        temporary = target.with_suffix(target.suffix + ".part")
        request = urllib.request.Request(spec["url"], headers={"User-Agent": "TRSM-runtime-bootstrap/1"})
        try:
            with urllib.request.urlopen(request, timeout=90) as response, temporary.open("wb") as stream:
                shutil.copyfileobj(response, stream)
            if sha256(temporary) != spec["sha256"]:
                raise SetupError(f"Checksum mismatch for {spec['url']}; expected {spec['sha256']}")
            temporary.replace(target)
        finally:
            temporary.unlink(missing_ok=True)
    if sha256(target) != spec["sha256"]:
        raise SetupError(f"Cached archive checksum mismatch: {target}")
    return target


def component_selection(requested):
    selected = set(requested) | {"python"}
    if "higgstools" in selected:
        selected.add("datasets")
    return tuple(name for name in COMPONENTS if name in selected)


def activation_text(prefix, components):
    prefix = Path(prefix)
    lines = ["# Generated by tools/bootstrap_runtime.py; source this file in bash or zsh.",
             f". {shlex.quote(str(prefix / 'venv/bin/activate'))}",
             f"export TRSM_RUNTIME_ROOT={shlex.quote(str(prefix))}"]
    if "datasets" in components:
        for key, folder in (("TRSM_HB_DATASET", "hbdataset"), ("TRSM_HS_DATASET", "hsdataset")):
            lines.append(f"export {key}={shlex.quote(str(prefix / 'sources' / folder))}")
    if "mg5" in components:
        lines.append(f"export TRSM_MG5_LOCATION={shlex.quote(str(prefix / 'MG5_aMC_v3_5_15'))}")
    return "\n".join(lines) + "\n"


def process_card(spec, *, jobs, fc, cxx, collier):
    return "\n".join([
        "set automatic_html_opening False", "set auto_update 0", f"set nb_core {jobs}",
        f"set fortran_compiler {fc}", f"set cpp_compiler {cxx}",
        f"set collier {collier}", "set ninja None", "set samurai None", "set golem None",
        "import model loop_sm_twoscalar_generic",
        "generate " + spec["generate"], "output " + spec["directory"], "quit", "",
    ])


def madgraph_subprocesses(process):
    """Read MG5's integration directories, excluding its PV loop libraries."""
    root = Path(process) / "SubProcesses"
    paths = []
    for name in (root / "subproc.mg").read_text().splitlines():
        name = name.strip()
        if not name:
            continue
        path = root / name
        if (path.resolve().parent != root.resolve()
                or not path.is_dir() or not (path / "makefile").is_file()):
            raise SetupError(f"Invalid generated subprocess directory: {name}")
        paths.append(path)
    if not paths:
        raise SetupError(f"No generated subprocesses in {process}")
    return paths


def check_bsmpt_startup(executable, env, log):
    command = [str(executable), "--help"]
    result = subprocess.run(command, env=env, stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    log.write("\n$ " + shlex.join(command) + "\n" + result.stdout)
    log.flush()
    # BSMPT 3.2.1 prints help and then checks its required physics arguments.
    # Accept that specific exit-1 response, while checking the TRSM model is
    # registered and rejecting loader failures or other unexpected errors.
    help_present = "CalcTemps calculates" in result.stdout and re.search(r"(?m)^trsm$", result.stdout)
    expected_exit = result.returncode == 0 or (
        result.returncode == 1 and "Not all required parameters are set." in result.stdout)
    if not help_present or not expected_exit:
        raise SetupError(f"BSMPT startup check failed ({result.returncode}): {executable}")


class Installer:
    def __init__(self, args, *, root=ROOT):
        self.args, self.root = args, Path(root)
        self.prefix = args.prefix.expanduser().resolve()
        self.cache = (args.download_cache or self.prefix / "downloads").expanduser().resolve()
        self.config = json.loads(args.sources.read_text())
        if self.config.get("schema") != 1:
            raise SetupError("Unsupported runtime source configuration")
        for spec in (*self.config["git"].values(), *self.config["higgs_dependencies"].values()):
            if not re.fullmatch(r"[0-9a-f]{40}", spec["commit"]):
                raise SetupError("Every Git source must be pinned to a full commit SHA")
        for spec in self.config["archives"].values():
            if not re.fullmatch(r"[0-9a-f]{64}", spec["sha256"]):
                raise SetupError("Every archive must have a SHA-256 digest")
            if Path(spec["filename"]).name != spec["filename"] or Path(spec["directory"]).name != spec["directory"]:
                raise SetupError("Archive names must be single path components")
        self.components = component_selection(args.components)
        self.processes = tuple(dict.fromkeys(args.mg5_process or PROCESSES))
        self.python = self.prefix / "venv/bin/python"
        self.state_path = self.prefix / STATE_NAME
        self.state = {}
        self.log = None
        self.recovering = False
        self.env = dict(os.environ)
        # Several upstream Makefiles update shared static archives. Their
        # serial builds must not inherit a caller's `make -j` configuration.
        for key in ("MAKEFLAGS", "GNUMAKEFLAGS", "MFLAGS", "MAKELEVEL", "MAKEOVERRIDES"):
            self.env.pop(key, None)
        self.env.update(TRSM_RUNTIME_ROOT=str(self.prefix),
                        CONAN_HOME=str(self.prefix / "conan"),
                        MPLCONFIGDIR=str(self.prefix / "matplotlib-cache"),
                        PYTHONNOUSERSITE="1", PYTHONUNBUFFERED="1",
                        CMAKE_BUILD_PARALLEL_LEVEL=str(args.jobs),
                        PATH=str(self.prefix / "venv/bin") + os.pathsep + os.environ.get("PATH", ""))
        for key, folder in (("TRSM_HB_DATASET", "hbdataset"), ("TRSM_HS_DATASET", "hsdataset")):
            self.env[key] = str(self.prefix / "sources" / folder)
        self.env["TRSM_MG5_LOCATION"] = str(self.prefix / "MG5_aMC_v3_5_15")
        apple = platform.system() == "Darwin"
        # Conan identifies named compiler drivers more reliably than `cc`.
        self.compilers = {key: os.environ.get(key, default) for key, default in
                          (("CC", "clang" if apple else "gcc"),
                           ("CXX", "clang++" if apple else "g++"), ("FC", "gfortran"))}
        self.env.update(self.compilers)

    def source_specs(self):
        names = []
        if "datasets" in self.components:
            names += ["hbdataset", "hsdataset"]
        if "higgstools" in self.components:
            names.append("higgstools")
        if "bsmpt" in self.components:
            names.append("bsmpt")
        if "mg5" in self.components:
            names.append("madgraph")
        specs = [(name, self.config["git"][name]) for name in names]
        if "higgstools" in self.components:
            specs += [("higgs-" + name, spec) for name, spec in self.config["higgs_dependencies"].items()]
        return specs

    def archive_specs(self):
        names = []
        if "micromegas" in self.components:
            names += ["micromegas-7.1.4", "micromegas-6.1.15"]
        if "mg5" in self.components:
            names.append("collier")
        return [(name, self.config["archives"][name]) for name in names]

    def plan(self):
        print(f"Runtime: {self.prefix}\nComponents: {', '.join(self.components)}")
        print(f"Python: {sys.executable}; required {self.config['python']}; build jobs: {self.args.jobs}")
        print("Python packages: config/runtime-requirements-v2.txt and config/build-requirements-v2.txt")
        for name, spec in self.source_specs():
            print(f"  git {name}: {spec['url']} @ {spec['commit']}")
        for name, spec in self.archive_specs():
            print(f"  archive {name}: {spec['url']}\n    sha256 {spec['sha256']}")
        if self.args.download_only:
            print("Download only: no compilation or activation script.")
            return
        if "higgstools" in self.components:
            print("  Build HiggsTools with the pinned FetchContent sources; load both datasets.")
        if "micromegas" in self.components:
            print("  Extract both releases; apply finite guard; build canonical TRSM model serially.")
        if "bsmpt" in self.components:
            print("  Apply TRSM/SM-input overlay; install Conan dependencies; build CalcTemps, MinimaTracer, PhaseProbe, Test.")
        if "mg5" in self.components:
            print("  Build COLLIER; install archived UFO; generate and compile:")
            for key in self.processes:
                spec = self.config["mg5_processes"][key]
                print(f"    {spec['generate']} -> {spec['directory']}")
        print("  Verify artifacts, write setup-manifest.json and activate.sh.")

    def preflight(self):
        if platform.system() not in ("Darwin", "Linux"):
            raise SetupError("This installer supports macOS and Linux.")
        if f"{sys.version_info.major}.{sys.version_info.minor}" != self.config["python"]:
            raise SetupError(f"Run this installer with Python {self.config['python']} (for example python3.13).")
        if any(c.isspace() for c in str(self.prefix) + str(self.root)):
            raise SetupError("Choose repository and runtime paths without whitespace; the native Makefiles require this.")
        required = ["git"]
        if not self.args.download_only:
            native = set(self.components) - {"python", "datasets"}
            if native:
                required += ["make", self.compilers["CC"], self.compilers["CXX"]]
            if native & {"micromegas", "mg5"}:
                required.append(self.compilers["FC"])
            if "micromegas" in native:
                required.append("patch")
            if "bsmpt" in native:
                required.append("rsync")
        missing = [name for name in required if not shutil.which(name)]
        if missing:
            raise SetupError("Missing build prerequisites: " + ", ".join(missing)
                             + ". See docs/runtime-bootstrap.md for the macOS/Linux package commands.")

    def identity(self):
        return {"schema": 1, "prefix": str(self.prefix), "repository": str(self.root),
                "download_cache": str(self.cache),
                "sources": self.config, "components": self.components, "mg5_processes": self.processes,
                "python": str(Path(sys.executable).absolute()), "python_version": platform.python_version(),
                "platform": platform.system(), "machine": platform.machine(),
                "compilers": self.compilers,
                "build_environment": {k: os.environ.get(k) for k in
                    ("CFLAGS", "CXXFLAGS", "FFLAGS", "LDFLAGS", "MACOSX_DEPLOYMENT_TARGET", "SDKROOT")},
                "source_files": source_fingerprint()}

    @contextmanager
    def workspace(self):
        if self.args.resume and not self.state_path.exists():
            raise SetupError("No bootstrap state exists to resume")
        if self.prefix.exists() and not self.state_path.exists() and any(self.prefix.iterdir()):
            raise SetupError(f"Refusing an existing unmanaged runtime: {self.prefix}. Choose a fresh prefix.")
        self.prefix.mkdir(parents=True, exist_ok=True)
        with (self.prefix / ".bootstrap.lock").open("a+") as lock:
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise SetupError("Another installer is using this prefix") from error
            identity = json.loads(json.dumps(self.identity()))
            if self.state_path.exists():
                if not self.args.resume:
                    raise SetupError("This prefix has setup state; use --resume to continue.")
                self.state = json.loads(self.state_path.read_text())
                if self.state.get("identity") != identity:
                    raise SetupError("Setup inputs changed; choose a fresh prefix (the download cache can be reused).")
            else:
                if self.args.resume:
                    raise SetupError("No bootstrap state exists to resume")
                self.state = {"identity": identity, "steps": {}}
                write_json(self.state_path, self.state)
            (self.prefix / "logs").mkdir(exist_ok=True)
            try:
                yield
            finally:
                fcntl.flock(lock, fcntl.LOCK_UN)

    def run(self, command, *, cwd=None, env=None):
        command = [str(item) for item in command]
        self.log.write("\n$ " + shlex.join(command) + "\n")
        self.log.flush()
        done = subprocess.run(command, cwd=cwd or self.root, env=self.env | (env or {}),
                              stdin=subprocess.DEVNULL, stdout=self.log, stderr=subprocess.STDOUT)
        if done.returncode:
            raise SetupError(f"Command failed ({done.returncode}): {shlex.join(command)}")

    def step(self, name, action):
        previous = self.state["steps"].get(name, {})
        if previous.get("status") == "done":
            for path, expected in previous["artifacts"].items():
                if not Path(path).is_file() or sha256(path) != expected:
                    raise SetupError(f"Completed artifact changed or is missing: {path}; use a fresh prefix.")
            if "git_checkout" in previous:
                checkout = previous["git_checkout"]
                modified = subprocess.check_output(["git", "-C", checkout, "status", "--porcelain",
                                                    "--untracked-files=no", "--ignore-submodules=none"], text=True)
                if modified.strip():
                    raise SetupError(f"Pinned upstream source has local edits: {checkout}")
            print(f"[skip] {name}", flush=True)
            return
        self.recovering = previous.get("status") in ("running", "failed")
        record = {"status": "running", "started_utc": datetime.now(timezone.utc).isoformat(),
                  "log": str(self.prefix / "logs" / (name + ".log"))}
        self.state["steps"][name] = record
        write_json(self.state_path, self.state)
        print(f"[build] {name} — {record['log']}", flush=True)
        try:
            with Path(record["log"]).open("a") as self.log:
                artifacts = action()
                record["artifacts"] = {str(p): sha256(p) for p in artifacts}
                record["status"] = "done"
        except BaseException as error:
            record.update(status="failed", error=str(error))
            raise
        finally:
            self.log = None
            write_json(self.state_path, self.state)

    def fresh(self, path):
        """Preserve a partial owned step before retrying, never overwrite it."""
        path = Path(path).resolve()
        if not path.is_relative_to(self.prefix) or path == self.prefix:
            raise SetupError(f"Build path escapes the selected prefix: {path}")
        if path.exists():
            if not self.recovering:
                raise SetupError(f"Refusing to overwrite {path}")
            history = self.prefix / "failed-builds"
            history.mkdir(exist_ok=True)
            backup = history / (path.name + "-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f"))
            path.rename(backup)
            self.log.write(f"Preserved partial build at {backup}\n")
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def clone(self, name, spec):
        target = self.fresh(self.prefix / "sources" / name)
        self.run(["git", "init", target])
        self.run(["git", "remote", "add", "origin", spec["url"]], cwd=target)
        self.run(["git", "fetch", "--depth", "1", "origin", spec["commit"]], cwd=target)
        self.run(["git", "checkout", "--detach", "FETCH_HEAD"], cwd=target)
        actual = subprocess.check_output(["git", "-C", str(target), "rev-parse", "HEAD"], text=True).strip()
        if actual != spec["commit"]:
            raise SetupError(f"Unexpected upstream revision for {name}: {actual}")
        if (target / ".gitmodules").is_file():
            self.run(["git", "submodule", "update", "--init", "--recursive"], cwd=target)
        self.state["steps"]["fetch-" + name]["git_checkout"] = str(target)
        return [target / ".git/HEAD"]

    def python_environment(self):
        target = self.fresh(self.prefix / "venv")
        self.run([sys.executable, "-m", "venv", target])
        self.run([self.python, "-m", "pip", "install", "--upgrade", "pip"])
        self.run([self.python, "-m", "pip", "install", "-r", self.root / "config/build-requirements-v2.txt",
                  "-r", self.root / "config/runtime-requirements-v2.txt"])
        return [target / "pyvenv.cfg"]

    def higgstools(self):
        source = self.prefix / "sources/higgstools"
        args = ["-DCMAKE_BUILD_TYPE=Release"]
        args += [f"-DFETCHCONTENT_SOURCE_DIR_{name.upper()}={self.prefix / 'sources' / ('higgs-' + name)}"
                 for name in self.config["higgs_dependencies"]]
        if platform.system() == "Darwin":
            args.append("-DCMAKE_CXX_FLAGS=-D_LIBCPP_TEMPLATE_VIS= -Wno-deprecated-literal-operator")
        self.run([self.python, "-m", "pip", "install", "--no-build-isolation", "--no-deps", source],
                 env={"CMAKE_ARGS": shlex.join(args)})
        receipt = self.prefix / "higgstools-installed.json"
        program = ("import importlib.util,json;from pathlib import Path; "
                   f"Path({str(receipt)!r}).write_text(json.dumps("
                   "{n:importlib.util.find_spec('Higgs.'+n).origin for n in ('_Higgs','predictions','bounds','signals')}))")
        self.run([self.python, "-c", program])
        extensions = [Path(p) for p in json.loads(receipt.read_text()).values()]
        return [receipt, *extensions]

    def micromegas(self, version):
        spec = self.config["archives"]["micromegas-" + version]
        target = self.fresh(self.prefix / spec["directory"])
        extract_source(self.cache / spec["filename"], target, spec["directory"])
        self.run(["sh", self.root / "DM/setup_micromegas.sh", target])
        self.run([target / "TRSM/main", "--capabilities"])
        return [target / "TRSM/main", target / "TRSM/main.c", target / "TRSM/lib/trsm_loop.c",
                *sorted((target / "TRSM/work/models").glob("*.mdl"))]

    def bsmpt(self):
        target = self.fresh(self.prefix / "BSMPT-3.2.1")
        self.run([self.python, self.root / "tools/stage_bsmpt_v2.py", self.prefix / "sources/bsmpt", target])
        conan = self.prefix / "venv/bin/conan"
        self.run([conan, "profile", "detect", "--force"])
        dependency_build = self.fresh(self.prefix / "build/bsmpt-conan")
        self.run([conan, "install", target, "--output-folder", dependency_build,
                  "--build=missing", "-s", "build_type=Release", "-s", "compiler.cppstd=17",
                  "-o", "&:EnableTests=False", "-c", f"tools.build:jobs={self.args.jobs}"])
        toolchains = list(dependency_build.rglob("conan_toolchain.cmake"))
        if len(toolchains) != 1:
            raise SetupError(f"Expected one Conan toolchain, found {toolchains}")
        self.run(["cmake", "-S", target, "-B", target / "build", "-DCMAKE_BUILD_TYPE=Release",
                  "-DCMAKE_TOOLCHAIN_FILE=" + str(toolchains[0]),
                  "-DBSMPTBuildExecutables=ON", "-DBUILD_TESTING=OFF"])
        names = ("CalcTemps", "MinimaTracer", "PhaseProbe", "Test")
        self.run(["cmake", "--build", target / "build", "--parallel", self.args.jobs, "--target", *names])
        return [target / "build/bin" / name for name in names]

    def collier(self):
        spec = self.config["archives"]["collier"]
        source = self.fresh(self.prefix / "build/collier")
        extract_source(self.cache / spec["filename"], source, spec["directory"])
        target = self.fresh(self.prefix / "collier")
        self.run(["cmake", "-S", source, "-B", source / "build", "-Dstatic=ON",
                  "-DCMAKE_Fortran_FLAGS=-fPIC", "-DCMAKE_BUILD_TYPE=Release",
                  "-DCMAKE_Fortran_COMPILER=" + self.compilers["FC"]])
        self.run(["cmake", "--build", source / "build", "--parallel", self.args.jobs])
        # MG5 searches for modules/ beside libcollier.a (or ../include/).
        (target / "modules").mkdir(parents=True)
        shutil.copy2(source / "libcollier.a", target / "libcollier.a")
        modules = list((source / "modules").glob("*.mod"))
        if not modules:
            raise SetupError("COLLIER built no Fortran module files")
        for path in modules:
            shutil.copy2(path, target / "modules" / path.name)
        return [target / "libcollier.a", *sorted((target / "modules").glob("*.mod"))]

    def madgraph(self):
        target = self.fresh(self.prefix / "MG5_aMC_v3_5_15")
        # Upstream templates contain relative links whose targets are supplied
        # only during process generation; preserve those links when staging.
        shutil.copytree(self.prefix / "sources/madgraph", target, symlinks=True,
                        ignore=shutil.ignore_patterns(".git", "__pycache__"))
        # Match upstream's release preparation: this developer-only script is
        # also the marker that triggers its "unknown development version" banner.
        (target / "bin/create_release.py").unlink(missing_ok=True)
        extract_source(self.root / "MG5stuff/loop_sm_twoscalar_generic.tar.gz",
                       target / "models/loop_sm_twoscalar_generic", "loop_sm_twoscalar_generic", ufo=True)
        # Avoid interactive dependency installation: use the pinned COLLIER
        # build plus MG5's bundled CutTools/IREGI fallback.
        configuration = target / "input/mg5_configuration.txt"
        defaults = target / "input/.mg5_configuration_default.txt"
        if defaults.is_file():
            shutil.copy2(defaults, configuration)
        with configuration.open("a") as stream:
            stream.write(f"\nautomatic_html_opening = False\nauto_update = 0\n"
                         f"fortran_compiler = {self.compilers['FC']}\ncpp_compiler = {self.compilers['CXX']}\n"
                         f"collier = {self.prefix / 'collier'}\nninja = None\n"
                         f"golem = None\nsamurai = None\nnb_core = {self.args.jobs}\n")
        return [target / "bin/mg5_aMC", target / "VERSION",
                target / "models/loop_sm_twoscalar_generic/parameters.py"]

    def process(self, key):
        mg5 = self.prefix / "MG5_aMC_v3_5_15"
        spec = self.config["mg5_processes"][key]
        target = self.fresh(mg5 / spec["directory"])
        card = self.prefix / "logs" / ("process-" + key + ".mg5")
        card.write_text(process_card(spec, jobs=self.args.jobs, fc=self.compilers["FC"],
                                     cxx=self.compilers["CXX"], collier=self.prefix / "collier"))
        self.run([self.python, mg5 / "bin/mg5_aMC", card], cwd=mg5)
        madevent = target / "bin/madevent"
        if not madevent.is_file():
            raise SetupError(f"MG5 did not generate {key}; inspect the process log")
        # These scans use central cross sections with MG5's bundled nn23lo1
        # PDFs. Explicitly disable the optional LHAPDF uncertainty pass.
        for name in ("run_card.dat", "run_card_default.dat"):
            path = target / "Cards" / name
            if path.is_file():
                value = re.sub(r"(?m)^\s*True\s*=\s*use_syst\b", " False = use_syst", path.read_text())
                value = re.sub(r"(?m)^\s*systematics\s*=\s*systematics_program\b", " none = systematics_program", value)
                path.write_text(value)
        self.run([self.python, madevent, "treatcards", "run"], cwd=target)
        self.run([self.python, madevent, "treatcards", "param"], cwd=target)
        self.run(["make", "-C", target / "Source"])
        subprocesses = madgraph_subprocesses(target)
        for path in subprocesses:
            command = ["make", "-C", path, "madevent"]
            originals = sorted(path.glob("matrix*_orig.f"))
            if originals and not any(path.glob("matrix*_optim.f")):
                # Tree exports prepare helicity recycling at the first run.
                # Compile the original matrix elements now without generating
                # events or changing MG5's runtime optimization settings.
                command.append("MATRIX=" + " ".join(p.with_suffix(".o").name for p in originals))
            self.run(command)
        return [madevent, target / "Cards/proc_card_mg5.dat", target / "SubProcesses/subproc.mg",
                *[p / "madevent" for p in subprocesses]]

    def verify(self):
        self.run([self.python, "-m", "pip", "check"])
        self.run([self.python, "-c", "import numpy,scipy,pandas,matplotlib;from trsm_flavour import flavour_configuration;flavour_configuration()"])
        if "higgstools" in self.components:
            self.run([self.python, "-c", "import math;from test_trsm_higgstools import ress_SM;assert math.isfinite(ress_SM);print('SM HiggsSignals chi2:',ress_SM)"])
        if "bsmpt" in self.components:
            check_bsmpt_startup(self.prefix / "BSMPT-3.2.1/build/bin/CalcTemps", self.env, self.log)
        artifacts = []
        if {"micromegas", "bsmpt", "higgstools"} <= set(self.components):
            # This checks installed native sources before issuing a receipt.
            self.run([self.python, self.root / "tools/runtime_manifest.py",
                      "--bsmpt-upstream", self.prefix / "sources/bsmpt",
                      "--higgstools-upstream", self.prefix / "sources/higgstools",
                      "--archive-dir", self.cache])
            artifacts.append(self.prefix / "runtime-manifest.json")
        freeze = self.prefix / "pip-freeze.txt"
        freeze.write_bytes(subprocess.check_output([str(self.python), "-m", "pip", "freeze"], env=self.env))
        activation = self.prefix / "activate.sh"
        activation.write_text(activation_text(self.prefix, self.components))
        receipt = self.prefix / "setup-manifest.json"
        write_json(receipt, {"schema": 1, "completed_utc": datetime.now(timezone.utc).isoformat(),
                            "identity": self.state["identity"],
                            "steps": {key: value for key, value in self.state["steps"].items() if key != "verify"},
                            "verification": "passed",
                            "mg5_pdf": "bundled nn23lo1; central cross sections, no uncertainty pass",
                            "loop_reduction": "COLLIER with bundled CutTools/IREGI fallback"})
        return [freeze, activation, receipt, *artifacts]

    def install(self):
        self.preflight()
        with self.workspace():
            if not self.args.download_only:
                self.step("python", self.python_environment)
            for name, spec in self.source_specs():
                self.step("fetch-" + name, lambda name=name, spec=spec: self.clone(name, spec))
            for name, spec in self.archive_specs():
                self.step("fetch-" + name, lambda spec=spec: [download_archive(spec, self.cache)])
            if self.args.download_only:
                print("Source downloads verified. Rerun with --resume and without --download-only to build.")
                return
            if "higgstools" in self.components:
                self.step("higgstools", self.higgstools)
            if "micromegas" in self.components:
                for version in ("7.1.4", "6.1.15"):
                    self.step("micromegas-" + version, lambda version=version: self.micromegas(version))
            if "bsmpt" in self.components:
                self.step("bsmpt", self.bsmpt)
            if "mg5" in self.components:
                self.step("collier", self.collier)
                self.step("madgraph", self.madgraph)
                for key in self.processes:
                    self.step("process-" + key, lambda key=key: self.process(key))
            self.step("verify", self.verify)
        print(f"Runtime ready. Activate it with:\n  source {shlex.quote(str(self.prefix / 'activate.sh'))}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", type=Path, required=True, help="Fresh, separate runtime directory")
    parser.add_argument("--jobs", type=int, default=min(4, os.cpu_count() or 1))
    parser.add_argument("--components", nargs="+", choices=COMPONENTS, default=list(COMPONENTS))
    parser.add_argument("--mg5-process", action="append", choices=PROCESSES,
                        help="Repeat to select processes; default: all four supported processes")
    parser.add_argument("--sources", type=Path, default=ROOT / "config/runtime-sources-v2.json")
    parser.add_argument("--download-cache", type=Path, help="Reusable directory of checksum-verified archives")
    parser.add_argument("--download-only", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="Print the plan without downloads or filesystem writes")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args(argv)
    if args.jobs < 1:
        parser.error("--jobs must be positive")
    return args


def main(argv=None):
    args = parse_args(argv)
    try:
        installer = Installer(args)
        installer.plan()
        if not args.dry_run:
            installer.install()
    except (SetupError, OSError, ValueError, subprocess.SubprocessError, tarfile.TarError) as error:
        print(f"Setup stopped: {error}\nSee step logs under {args.prefix / 'logs'}.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
